### ISSUE TITLE
Time doesn't display on polybar

### ISSUE THREAD

**Issue by nowhereandgoodbye** [darch7/bspwmbydarch#6]
The time doesn't display on polybar. I only see a clock symbol and PM.

Everything else works fine.

**Comment by darch7** [comment]
date | awk '{ print $5}' | cut -c 1-5


It is a script error Bar_Hora Please put this line in your Normal user terminal without root and see if it shows you the time in case you do the space or syntax error in the Polybar config. Otherwise you do not show you the time it should be a problem that you lack a package sñ

**Comment by darch7** [comment]
change the time script, located in ./local/bin/modules/bar_time and put it like this in the image reload bspwm and I think that will fix it


![image](https://user-images.githubusercontent.com/70046164/106399553-10cf6a80-63f8-11eb-84c4-9e34a34ebf5a.png)

**Comment by darch7** [comment]
> The time doesn't display on polybar. I only see a clock symbol and PM.
> 
> Everything else works fine.


change the time script, located in ./local/bin/modules/bar_time and put it like this in the image reload bspwm and I think that will fix it


![image](https://user-images.githubusercontent.com/70046164/106399613-85a2a480-63f8-11eb-971b-5908edb709e7.png)

**Comment by nowhereandgoodbye** [comment]
Thanks, I finally got it working by using quotation marks to bar_hora 

hora=$(date +"%H:%M")
echo "$hora"
